### ISSUE TITLE
[github-actions] script check fails frequently

### ISSUE THREAD

**Issue by jwhui** [openthread/ot-br-posix#786]
[logs_6926.zip](https://github.com/openthread/ot-br-posix/files/6297333/logs_6926.zip)

**Comment by simonlingoogle** [comment]
This issue seems to happen a lot recently. 

```
2021-04-12T01:37:39.3157932Z otbr-agent[19207]: [adproxy] Stopped
2021-04-12T01:37:39.3162790Z otbr-agent[19207]: Initialize OpenThread Border Router Agent: OK
2021-04-12T01:37:39.3177631Z otbr-agent[19207]: Border router agent started.
2021-04-12T01:37:39.3182980Z otbr-agent[19207]: [INFO]-CORE----: Notifier: StateChanged (0x00038200) [NetData PanId NetName ExtPanId]
2021-04-12T01:37:39.3216581Z otbr-agent[19207]: [INFO]-PLAT----: Host netif is down
2021-04-12T01:37:39.3223194Z otbr-agent[19207]: [INFO]-BR------: infra interface state changed: RUNNING, link-local-addr=fe80:0:0:0:20d:3aff:fec5:f141
2021-04-12T01:37:39.3249345Z otbr-agent[19207]: [INFO]-BR------: infra interface state changed: RUNNING, link-local-addr=fe80:0:0:0:20d:3aff:fec5:f141
2021-04-12T01:37:44.2001546Z ##[error]Process completed with exit code 1.
```
`otbr-agent` just exit unexpectedly without further information.
Currently, I don't have any clue on this issue.

**Comment by simonlingoogle** [comment]
Not sure if I reproduced the exact same issue, but I got this core dump when running `script-check` in ubuntu focal docker:

```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ff838347859 in __GI_abort () at abort.c:79
#2  0x00007ff8385cd951 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ff8385d947c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ff8385d94e7 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ff8385d9799 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x0000561da0c62d35 in void boost::throw_exception<boost::system::system_error>(boost::system::system_error const&) ()
#7  0x0000561da0c5876e in boost::asio::detail::do_throw_error(boost::system::error_code const&, char const*) ()
#8  0x0000561da0c583b0 in boost::asio::detail::throw_error(boost::system::error_code const&, char const*) ()
#9  0x0000561da0c6e0b3 in boost::asio::basic_socket_acceptor<boost::asio::ip::tcp, boost::asio::executor>::bind(boost::asio::ip::basic_endpoint<boost::asio::ip::tcp> const&) ()
#10 0x0000561da0c67917 in SimpleWeb::ServerBase<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor> >::start() ()
#11 0x0000561da0c54c17 in otbr::Web::WebServer::StartWebServer(char const*, char const*, unsigned short) ()
#12 0x0000561da0c4fa57 in main ()
```

note that this crash is of `otbr-web` problem, not `otbr-agent`. 

Is it possible any recent change has caused this crash? @jwhui @bukepo

**Comment by simonlingoogle** [comment]
This issue may have been caused by #782. See #794.
